### ISSUE TITLE
Join forces?

### ISSUE THREAD

**Issue by 12people** [AdiAr11/7MinutesWorkout#1]
Hey,

You contributed to Time Cop recently, I took a glance at your account, and just happened to notice you have a similar project to mine. Here's my open-source workout app: https://gitlab.com/enjoyingfoss/feeel . I'm also collaborating with wger, which has a slightly different focus, but there's a lot of overlap: https://github.com/wger-project/flutter .

If this is a space you're interested in, perhaps we could join forces and push it forward together. :)

(Sorry for using issue for this — as I don't use social media, I didn't find a better way to contact you.)

**Comment by AdiAr11** [comment]
Hi @12people , sure that'd be great!

**Comment by 12people** [comment]
Awesome!

Just to be clear, this isn't a job offer or anything (on a reread of my post, I'm thinking I could've worded things better) — both me and the author of wger are working on these projects in our spare time. However, if you're interested in open-source and in this space, we could perhaps do a Jitsi call sometime so that I could let you know where these projects are and what the current plans are.

I just wrote you an email, let me know if you'd like to talk. :)
